config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'

  resources :tasks do
    member do
      patch :file_purge
    end
  end

  resources :users, only: [:new, :create, :show]
  resources :labels, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources :labels, only: [:new, :create, :destroy]
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :groups
  resources :groupings, only: [:create, :destroy]
end

app/models/task.rb
class Task < ApplicationRecord
  enum status: { 未着手:0, 着手:1, 完了:2 }
  enum priority: { 不急:1, 低:2, 中:3, 高:4, 緊急:5}

  validates :task_name,  presence: true
  validates :content, presence: true
  validates :priority,  presence: true
  validates :task_expired_at, presence: true
  validates :status,  presence: true

  scope :title_searched, -> (title){ where('task_name LIKE ?',"%#{title}%") }
  scope :status_searched, -> (status){ where(status: status) }
  scope :label_searched, -> (label_id){ where(id: Labelling.where(label_id: label_id).pluck(:task_id)) }

  scope :limit_sorted, -> { order(task_expired_at: "DESC") }
  scope :created_sorted, -> { order(created_at: "DESC") }
  scope :priority_sorted, -> { order(priority: "DESC") }

  belongs_to :user
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings

  has_many_attached :task_files

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :file_purge]
  before_action :authenticate_user, only: [:index, :show, :new, :edit]
  before_action :task_different_user, only: [:show, :edit, :destroy]
  before_action :get_available_labels, only: [:index, :new, :create, :edit, :update]

  def index
    if params[:commit] == "検索"
      @searched_words = {}
      @searched_words.store("タスク名", params[:title]) if params[:title].present?
      @searched_words.store("ラベル", Label.find(params[:label_id]).label_name) if params[:label_id].present?
      @searched_words.store("ステータス", params[:status]) if params[:status].present?
    end
    if params[:sort_limit]
      @tasks = current_user.tasks.limit_sorted.page(params[:page]).per(10)
    elsif params[:sort_priority]
      @tasks = current_user.tasks.priority_sorted.page(params[:page]).per(10)

    elsif params[:title].present? && params[:status].present? && params[:label_id].present?
      @tasks = current_user.tasks.title_searched(params[:title]).status_searched(params[:status]).label_searched(params[:label_id]).page(params[:page]).per(10)

    elsif params[:title].present? && params[:status].present?
      @tasks = current_user.tasks.title_searched(params[:title]).status_searched(params[:status]).page(params[:page]).per(10)
    elsif params[:title].present? && params[:label_id].present?
      @tasks = current_user.tasks.title_searched(params[:title]).label_searched(params[:label_id]).page(params[:page]).per(10)
    elsif params[:status].present? && params[:label_id].present?
      @tasks = current_user.tasks.status_searched(params[:status]).label_searched(params[:label_id]).page(params[:page]).per(10)

    elsif params[:title].present?
      @tasks = current_user.tasks.title_searched(params[:title]).page(params[:page]).per(10)
    elsif params[:status].present?
      @tasks = current_user.tasks.status_searched(params[:status]).page(params[:page]).per(10)
    elsif params[:label_id].present?
      @tasks = current_user.tasks.label_searched(params[:label_id]).page(params[:page]).per(10)

    else
      @tasks = current_user.tasks.created_sorted.page(params[:page]).per(10)
    end
    @task_expired = Task.where(user_id:current_user.id).where("task_expired_at<?",Time.zone.today+2).where.not(status:"完了")
  end

  def show
    @labels = @task.labels
  end

  def file_purge
    params[:task][:task_file_ids].each do |task_file_id|
      file = @task.task_files.find(task_file_id)
      file.purge
    end
    redirect_to @task, notice: 'ファイルを削除しました'
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to @task, notice: t('notice.task_created')
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to @task, notice: t('notice.task_updated')
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: t('notice.task_deleted')
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:task_name, :priority, :task_expired_at, :status, :content, label_ids: [], task_files: [])
  end

  def task_different_user
    @task = Task.find(params[:id])
    if current_user.id != @task.user_id
      redirect_to tasks_path, notice: "他のユーザーのタスクは見れません"
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def official_or_user_label(label)
    if label.official?
      "official_label official_label_task_new"
    else
      "user_label"
    end
  end
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, t('errors.count')) %><%= t('errors.explanation') %></h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="form_table">
    <div class="field">
      <tr>
        <th><%= form.label :task_name %></th>
        <td><%= form.text_field :task_name %></td>
      </tr>
    </div>
    <div class="field">
      <tr>
        <th><%= form.label :content %></th>
        <td><%= form.text_field :content %></td>
      </tr>
    </div>
    <div class="field">
      <tr>
        <th><%= form.label :priority %></th>
        <td><%= form.select :priority, Task.priorities.keys %></td>
      </tr>
    </div>
    <div class="field">
      <tr>
        <th><%= form.label :task_expired_at, id: "task_limit" %></th>
        <td><%= form.date_select :task_expired_at %></td>
      </tr>
    </div>
    <div class="field">
      <tr>
        <th><%= form.label :status %></th>
        <td>
          <% Task.statuses.each do |key,val| %>
            <label><%= form.radio_button :status, key %><%= key %></label>
          <% end %>
        </td>
      </tr>
    </div>
    <div class="field">
      <tr>
        <th>ラベル</th>
        <td>
          <% labels.each do |label| %>
            <%= form.check_box :label_ids, {multiple: true, checked: @task.labels.include?(label), disabled: label[:disabled], include_hidden: false }, label[:id] %>
            <%= content_tag :span, label.label_name, class: official_or_user_label(label) %>
          <% end %>
        </td>
      </tr>
    </div>
    <div class="field">
      <tr>
        <th>添付ファイル</th>
        <td><%= form.file_field :task_files, multiple: true %></td>
      </tr>
    </div>
  </table>

  <div class="actions">
    <%= form.submit class: "new_submit_btn btn btn-primary new_btn"%>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="container-fluid base_bg">
  <div class="container main">
    <div class="new_main_wrapper">

      <h1><%= t('titles.task_title_edit') %></h1>

      <%= render 'form', task: @task, labels: @labels %>

      <%= link_to t('buttons.task_show'), @task %> |
      <%= link_to t('buttons.back'), tasks_path %>

    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container-fluid base_bg">
  <div class="container main">
    <div class="main_wrapper">
      <p id="notice"><%= notice %></p>

      <h1><%= t('titles.task_title_index') %></h1>

      <% if @task_expired.present? %>
        <div class="task_expired task_expired_index">
          <p>以下のタスクは2日以内に遂行期限が過ぎるか、すでに過ぎています！</p>
          <table id="task_expired_table_index">
            <% @task_expired.each do |expired| %>
              <tr>
                <td>タスク名:『<%= expired.task_name %>』</td>
                <td>優先度:『<%= expired.priority %>』</td>
                <td>期限:<%= expired.task_expired_at %></td>
                <td><%= expired.status %></td>
              </tr>
            <% end %>
          </table>
        </div>
      <% end %>

      <% if @searched_words %>
        <ul class="above_searched_words">次のワードで検索しました
          <li class="searched_words">
            <% @searched_words.each do |key,value| %>
              <span class="searched_key"><%= "#{key}:"%></span>
              <span class="searched_value"><%= "『#{value}』" %></span>
            <% end %>
          </li>
        </ul>
      <% end %>

      <div class="search_form">
        <%= form_with url: tasks_path, method: :get, local: true do |form| %>
          <%= form.label :title , t('activerecord.attributes.task.task_name') %>
          <%= form.text_field :title %>
          <label for="label_id">ラベル</label>
          <%= form.select :label_id, @labels.collect {|l| [l.label_name, l.id]}, include_blank: true %>
          <%= form.label :status, t('activerecord.attributes.task.status'), class: "status_search_label" %>
          <%= form.select :status, Task.statuses.keys, {include_blank: true} %>
          <%= form.submit '検索' , class: "btn btn-primary search_button"%>
        <% end %>
      </div>



      <%= link_to "優先順位でソートする", tasks_path(sort_priority: "true"), id: "sort_priority_button" %>
      <%= link_to "終了期限でソートする", tasks_path(sort_limit: "true"), id: "sort_limit_button" %>

      <table class="table table-hover">
        <thead>
          <tr class="table_ths">
            <th class="first_th task_title_th"><%= t('activerecord.attributes.task.task_name') %></th>
            <th class="task_content_th"><%= t('activerecord.attributes.task.content') %></th>
            <th class="task_label_th">ラベル</th>
            <th class="task_priority_th">
              <%= link_to "#{t('activerecord.attributes.task.priority')} ▼", tasks_path(sort_priority: "true"), id: "sort_priority_button" %>
            </th>
            <th class="task_limit_th" id="task_limit_th_id">
              <%= link_to "#{t('activerecord.attributes.task.limit')} ▼", tasks_path(sort_limit: "true"), id: "sort_limit_button" %>
            </th>
            <th class="task_status_th"><%= t('activerecord.attributes.task.status') %></th>
            <th class="task_created_at_th"><%= t('activerecord.attributes.task.created_at') %></th>
            <th colspan="3" class="last_th task_btns_th"></th>
          </tr>
        </thead>

        <tbody class="task_tbody">
          <% @tasks.each do |task| %>
            <tr>
              <td class="task_title"><%= task.task_name %></td>
              <td><%= task.content %></td>
              <td>
                <% task.labels.each do |label| %>
                  <% if label.official? %>
                    <span class="official_label label_index"><%= label.label_name %></span>
                  <% else %>
                    <span class="user_label label_index"><%= label.label_name %></span>
                  <% end %>
                <% end %>
              </td>
              <td class="task_priority"><%= task.priority %></td>
              <td class="task_limit"><%= content_tag :span, task.task_expired_at, class: expired_or_not(task) %></td>
              <td class="task_status"><%= task.status %></td>
              <td class="task_created_at"><%= l task.created_at %></td>
              <td><%= link_to t('buttons.task_show'), task, class: "btn btn-default btn_show"%></td>
              <td><%= link_to t('buttons.task_edit'), edit_task_path(task), class: "btn btn-default btn_edit" %></td>
              <td><%= link_to t('buttons.task_delete'), task, class: "btn btn-default btn_delete", method: :delete, data: { confirm: t('confirm.when_delete') } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @tasks %>
      <br>

      <%= link_to t('buttons.task_new'), new_task_path, class: "btn btn-primary new_btn" %>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container-fluid base_bg">
  <div class="container main">
    <div class="new_main_wrapper">

      <h1><%= t('titles.task_title_new') %></h1>

      <%= render 'form', task: @task, labels: @labels %>

      <%= link_to t('buttons.back'), tasks_path %>

    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container-fluid base_bg">
  <div class="container main">
    <div class="new_main_wrapper">

      <p id="notice"><%= notice %></p>

      <h1>タスク詳細</h1>

      <table class="show_table">
        <tr>
          <th><%= t('activerecord.attributes.task.task_name') %></th>
          <td><%= @task.task_name %></td>
        </tr>
        <tr>
          <th><%= t('activerecord.attributes.task.content') %></th>
          <td><%= @task.content %></td>
        </tr>
        <tr>
          <th><%= t('activerecord.attributes.task.priority') %></th>
          <td><%= @task.priority %></td>
        </tr>
        <tr>
          <th><%= t('activerecord.attributes.task.limit') %></th>
          <td><%= @task.task_expired_at %></td>
        </tr>
        <tr>
          <th><%= t('activerecord.attributes.task.status') %></th>
          <td><%= @task.status %></td>
        </tr>
        <tr>
          <th><%= t('activerecord.attributes.task.created_at') %></th>
          <td><%= l @task.created_at %></td>
        </tr>
        <tr>
          <th>ラベル</th>
          <td>
            <% @labels.each do |label| %>
              <% if label.official? %>
                <span class="official_label"><%= label.label_name %></span>
              <% else %>
                <span class="user_label"><%= label.label_name %></span>
              <% end %>
            <% end %>
          </td>
        </tr>

      </table>

      <% if @task.task_files.attached? %>
        <%= form_with model: @task, local: true, url: file_purge_task_path(@task.id)  do |form| %>
          <p>現在登録されているファイル（削除するものはチェックしてください）</p>
          <ul>
            <% @task.task_files.each do |task_file| %>
              <li>
              <%binding.pry%>
                <%= form.check_box :task_file_ids, {:multiple => true}, task_file.id, false %>
                <% fullfilename = rails_blob_path(task_file) %>
                <% if File.extname(fullfilename).downcase == ".pdf" %>
                  <%= image_tag task_file.blob.preview(resize: "300x300") %>
                <% else %>
                  <%= image_tag task_file.variant(resize: "300x300") %>
                <% end %>
              </li>
            <% end %>
          </ul>
          <%= form.submit %>
        <% end %>
      <% end %>

      <div class="show_btns">
        <%= link_to t('buttons.task_edit'), edit_task_path(@task), class: "btn btn-default btn_edit" %>
        <%= link_to t('buttons.task_delete'), @task, class: "btn btn-default btn_delete", method: :delete, data: { confirm: '本当に削除してもいいですか？' } %>
      </div>

      <%= link_to t('buttons.back'), tasks_path %>

    </div>
  </div>
</div>