config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'

  resources :tasks do
    member do
      patch :file_purge
    end
  end

  resources :users, only: [:new, :create, :show]
  resources :labels, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources :labels, only: [:new, :create, :destroy]
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :groups
  resources :groupings, only: [:create, :destroy]
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :groupings, dependent: :destroy
  has_many :users, through: :groupings
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :only_owner, only: [:edit, :update, :destroy]
  before_action :only_member, only: [:show]

  def index
    @groups = Group.all
  end

  def show
    @members = @group.users
    @group_tasks = Task.where(user_id:@members.pluck(:id))
    if params[:sort_limit]
      @group_tasks = Task.where(user_id:@members.pluck(:id)).limit_sorted.page(params[:page]).per(10)
    elsif params[:sort_priority]
      @group_tasks = Task.where(user_id:@members.pluck(:id)).priority_sorted.page(params[:page]).per(10)
    else
      @group_tasks = Task.where(user_id:@members.pluck(:id)).created_sorted.page(params[:page]).per(10)
    end
  end

  def new
    @group = Group.new
  end

  def edit
  end

  def create
    @group = current_user.groups.new(group_params)
    if @group.save
      current_user.groupings.create!(group_id:@group.id)
      redirect_to @group, notice: 'グループを作成しました！'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to @group, notice: 'グループを更新しました'
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_url, notice: 'グループを削除しました'
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:group_name, :group_detail)
  end

  def only_owner
    if current_user.id != @group.user.id
      redirect_to groups_path, notice: 'グループ作成者のみ可能です'
    end
  end

  def only_member
    unless @group.users.include?(current_user)
      redirect_to groups_path, notice: 'グループ参加者のみ可能です'
    end
  end
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="form_table">
    <div class="field">
      <tr>
        <th><%= form.label :group_name %></th>
        <td><%= form.text_field :group_name %></td>
      </tr>
    </div>
    <div class="field">
      <tr>
        <th><%= form.label :group_detail %></th>
        <td><%= form.text_field :group_detail %></td>
      </tr>
    </div>

  </table>

  <div class="actions">
    <%= form.submit class: "new_submit_btn btn btn-primary new_btn"%>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class="container-fluid base_bg">
  <div class="container main">
    <div class="new_main_wrapper">
      <h1>グループ更新</h1>

      <%= render 'form', group: @group %>

      <%= link_to t('buttons.task_show'), @group %> |
      <%= link_to t('buttons.back'), groups_path %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container-fluid base_bg">
  <div class="container main">
    <div class="main_wrapper">
      <p id="notice"><%= notice %></p>

      <h1>グループ一覧</h1>

      <table class="table table-hover group_table_index">
        <thead>
          <tr class="group_table_ths">
            <th class="first_th"> </th>
            <th>グループ名</th>
            <th>詳細</th>
            <th>参加人数</th>
            <th>オーナー</th>
            <th colspan="3" class="last_th group_btns_th"></th>
          </tr>
        </thead>

        <tbody>
          <% @groups.each do |group| %>
            <tr>
              <% if current_user.id == group.user.id %>
                <td class="group_table_owner_td">オーナー</td>
              <% elsif group.users.include?(current_user) %>
                <td class="group_table_member_td">参加中</td>
              <% else %>
                <td></td>
              <% end %>
              <td><%= group.group_name %></td>
              <td><%= group.group_detail %></td>
              <td><%= group.users.count %></td>
              <td><%= group.user.name %></td>

              <% if group.user.id == current_user.id %>
                <td><%= link_to '詳細', group %></td>
                <td><%= link_to '編集', edit_group_path(group) %></td>
                <td><%= link_to '削除', group, method: :delete, data: { confirm: '本当に削除してもいいですか？' } %></td>
              <% elsif group.users.include?(current_user) %>
                <td><%= link_to '詳細', group %></td>
                <td><%= link_to 'グループから離脱する', grouping_path(id:current_user.groupings.find_by(group_id:group.id).id, current_user_id:current_user.id), method: :delete, data: { confirm: '本当に離脱してもいいですか？' } %></td>
                <td></td>
              <% else %>
                <td><%= link_to 'グループに参加する', groupings_path(group_id:group.id), method: :post, data: { confirm: '本当に参加してもいいですか？'} %></td>
              <% end %>

            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'グループ作成', new_group_path, class: "btn btn-primary new_btn" %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container-fluid base_bg">
  <div class="container main">
    <div class="new_main_wrapper">

      <h1>グループ作成</h1>

      <%= render 'form', group: @group %>

      <%= link_to '戻る', groups_path %>

    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container-fluid base_bg">
  <div class="container main">
    <div class="new_main_wrapper">
      <p id="notice"><%= notice %></p>

      <h1><%= @group.group_name %>グループ</h1>

      <table class="group_members_table">
        <tr>
          <th>オーナー</th>
          <td><%= @group.user.name %></td>
        </tr>
        <tr>
          <th>参加者</th>
          <td><%= @members.pluck(:name).join('　') %></td>
        </tr>
      </table>

      <table class="table table-hover group_table_index">
        <thead>
          <tr class="group_table_ths">
            <th class="first_th task_title_th"><%= t('activerecord.attributes.task.task_name') %></th>
            <th class="task_content_th"><%= t('activerecord.attributes.task.content') %></th>
            <th class="task_label_th">ラベル</th>
            <th class="task_priority_th">
              <%= link_to "#{t('activerecord.attributes.task.priority')} ▼", group_path(id:@group.id, sort_priority: "true"), id: "sort_priority_button" %>
            </th>
            <th class="task_limit_th" id="task_limit_th_id">
              <%= link_to "#{t('activerecord.attributes.task.limit')} ▼", group_path(id:@group.id, sort_limit: "true"), id: "sort_limit_button" %>
            </th>
            <th class="task_status_th"><%= t('activerecord.attributes.task.status') %></th>
            <th class="task_created_at_th"><%= t('activerecord.attributes.task.created_at') %></th>
          </tr>
        </thead>

        <tbody class="task_tbody">
          <% @group_tasks.each do |task| %>
            <tr>
              <td class="task_title"><%= task.task_name %></td>
              <td><%= task.content %></td>
              <td>
                <% task.labels.each do |label| %>
                  <% if label.official? %>
                    <span class="official_label label_index"><%= label.label_name %></span>
                  <% else %>
                    <span class="user_label label_index"><%= label.label_name %></span>
                  <% end %>
                <% end %>
              </td>
              <td class="task_priority"><%= task.priority %></td>
              <td class="task_limit"><%= content_tag :span, task.task_expired_at, class: expired_or_not(task) %></td>
              <td class="task_status"><%= task.status %></td>
              <td class="task_created_at"><%= l task.created_at %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @group_tasks %>

      <p><%= link_to t('buttons.back'), groups_path %></p>
    </div>
  </div>
</div>