config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'

  resources :tasks do
    member do
      patch :file_purge
    end
  end

  resources :users, only: [:new, :create, :show]
  resources :labels, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources :labels, only: [:new, :create, :destroy]
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :groups
  resources :groupings, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! }
  before_destroy :label_manager_check_destroy
  before_destroy :admin_count_check
  before_save :label_manager_check_save
  before_update :admin_edit_check

  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :tasks, dependent: :destroy
  has_many :labels, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :groupings, dependent: :destroy
  has_many :joined_groups, through: :groupings, source: :group

  private

  def admin_count_check
    throw(:abort) if self.admin && User.where(admin: true).count == 1
  end

  def admin_edit_check
    if self.admin_was && self.admin_changed? && User.where(admin: true).count == 1
      errors.add :base, '最後の管理ユーザーです'
      throw :abort
    end
  end

  def label_manager_check_destroy
    throw(:abort) if self.admin && self.name =="official_label_manager"
  end

  def label_manager_check_save
    if self.name == "official_label_manager" && User.where(admin: true).count == 1
      errors.add :base, 'この名前は使用できません'
      throw :abort
    elsif self.name_was == "official_label_manager"
      errors.add :base, 'この名前は変更できません'
      throw :abort
    end
  end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_user
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.eager_load(:tasks).order(created_at: "DESC").page(params[:page]).per(15)
    @labels = Label.where(official:true)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: 'ユーザーを作成しました！'
    else
      render :new
    end
  end

  def show
    @tasks = @user.tasks.created_sorted.page(params[:page]).per(10)
    @labels = Label.where(user_id:@user.id, official:false)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: 'ユーザー情報を更新しました！'
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: 'ユーザーを削除しました！'
    else
      redirect_to admin_users_path, notice: 'official_label_managerは削除できません'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :favorites]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path(@user.id), notice: 'ユーザー登録が完了しました！'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path, notice: 'ユーザー情報を更新しました！'
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  before_action :authenticate_user, only: [:show]
  before_action :fobid_login_user, only: [:new]
  before_action :user_different, only: [:show]
  before_action :get_available_labels, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = User.last.id
      redirect_to tasks_path, notice: 'ユーザー登録が完了しました！'
    else
      render :new
    end
  end

  def show
    @tasks = @user.tasks.created_sorted.page(params[:page]).per(10)
    @task_expired = Task.where(user_id:@user.id).where("task_expired_at<?",Time.zone.today+2).where.not(status:"完了")
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def user_different
    unless current_user.admin?
      @user = User.find(params[:id])
      if current_user.id != @user.id
        redirect_to tasks_path, notice: "他のユーザーの情報は見れません"
      end
    end
  end
end

app/views/admin/users/edit.html.erb
<div class="container-fluid base_bg">
  <div class="container main">
    <div class="user_new_wrapper">

      <h1 class="admin_index_h1">ユーザー編集（管理画面）</h1>

      <%= form_with(model: @user, local: true, url: admin_user_path ) do |form| %>

        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2>登録中に<%= pluralize(@user.errors.count, "個") %>のエラーが発生しました</h2>
            <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <table class="form_table user_form">
          <div class="field">
            <tr>
              <th><%= form.label :name %></th>
              <td><%= form.text_field :name %></td>
            </tr>
          </div>
          <div class="field">
            <tr>
              <th><%= form.label :email %></th>
              <td><%= form.text_field :email %></td>
            </tr>
          </div>
          <div class="field">
            <tr>
              <th><%= form.label :password %></th>
              <td><%= form.password_field :password %></td>
            </tr>
          </div>
          <div class="field">
            <tr>
              <th><%= form.label :password_confirmation %></th>
              <td><%= form.password_field :password_confirmation %></td>
            </tr>
          </div>
          <div class="field">
            <tr>
              <th>権限</th>
              <td>
                <%= form.radio_button :admin, :true %>
                <%= form.label :admin, "管理者", {value: :true, style: "display: inline-block;"} %>
                <%= form.radio_button :admin, :false %>
                <%= form.label :admin, "一般", {value: :true, style: "display: inline-block;"} %>
              </td>
            </tr>
          </div>
        </table>
        <div class="actions">
          <%= form.submit class: "new_submit_btn btn btn-primary admin_new_btn" %>
        </div>
      <% end %>
      <div class="show_btns">
        <%= link_to t('buttons.back'), admin_users_path %>
      </div>

    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container-fluid base_bg">
  <div class="container main">
    <div class="main_wrapper">
      <p id="notice"><%= notice %></p>

      <h1 class="admin_index_h1">公式ラベル一覧（管理画面）</h1>
      <div>
        <ul class="official_labels">
          <% @labels.each do |label| %>
            <li class="official_labels_li">
              <span class="official_label"><%= label.label_name %></span>
              <%= link_to admin_label_path(label.id), method: :delete, class: "label_delete_link", data: { confirm: t('confirm.when_delete') } do %>
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-x" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
</svg>
              <% end %>
            </li>
          <% end %>
          <li class="official_labels_li">
            <%= link_to "公式ラベルを作成", new_admin_label_path, class: "btn btn-primary admin_new_btn" %>
          </li>
        </ul>
      </div>

      <h1 class="admin_index_h1">ユーザー一覧（管理画面）</h1>

      <table class="user_index">
        <tr>
          <th><%= t('activerecord.attributes.user.id') %></th>
          <th>権限</th>
          <th><%= t('activerecord.attributes.user.name') %></th>
          <th><%= t('activerecord.attributes.user.email') %></th>
          <th><%= t('activerecord.attributes.user.created_at') %></th>
          <th><%= t('activerecord.attributes.user.task_counts') %></th>
          <th colspan="3"></th>
        </tr>

        <% @users.each do |user| %>

          <tr>
            <td><%= user.id %></td>
            <td class="admin_sign"><%= "管理者" if user.admin? %></td>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= l user.created_at %></td>
            <td><%= user.tasks.length %></td>
            <td><%= link_to t('buttons.task_show'), admin_user_path(user) %></td>
            <td><%= link_to t('buttons.task_edit'), edit_admin_user_path(user) %></td>
            <td><%= link_to t('buttons.task_delete'), admin_user_path(user), class: "user_destroy", method: :delete, data: { confirm: t('confirm.when_delete') } %></td>
          </tr>

        <% end %>
      </table>
      <%= paginate @users %>

      <%= link_to "ユーザーを新規作成", new_admin_user_path, class: "btn btn-primary admin_new_btn" %>


    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="container-fluid base_bg">
  <div class="container main">
    <div class="user_new_wrapper">

      <h1 class="admin_index_h1">ユーザー作成（管理画面）</h1>
      <%= form_with(model: @user, local: true, url: admin_users_path ) do |form| %>

        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2>登録中に<%= pluralize(@user.errors.count, "個") %>のエラーが発生しました</h2>
            <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <table class="form_table user_form">
          <div class="field">
            <tr>
              <th><%= form.label :name %></th>
              <td><%= form.text_field :name %></td>
            </tr>
          </div>
          <div class="field">
            <tr>
              <th><%= form.label :email %></th>
              <td><%= form.text_field :email %></td>
            </tr>
          </div>
          <div class="field">
            <tr>
              <th><%= form.label :password %></th>
              <td><%= form.password_field :password %></td>
            </tr>
          </div>
          <div class="field">
            <tr>
              <th><%= form.label :password_confirmation %></th>
              <td><%= form.password_field :password_confirmation %></td>
            </tr>
          </div>
          <div class="field">
            <tr>
              <th>権限</th>
              <td>
                <%= form.radio_button :admin, :true %>
                <%= form.label :admin, "管理者", {value: :true, style: "display: inline-block;"} %>
                <%= form.radio_button :admin, :false %>
                <%= form.label :admin, "一般", {value: :true, style: "display: inline-block;"} %>
              </td>
            </tr>
          </div>
        </table>
        <div class="actions">
          <%= form.submit class: "new_submit_btn btn btn-primary admin_new_btn" %>
        </div>
      <% end %>
      <div class="show_btns">
        <%= link_to t('buttons.back'), admin_users_path %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container-fluid base_bg">
  <div class="container main">
    <div class="user_new_wrapper">

      <div class="user_show_content">
        <h1 class="admin_index_h1">ユーザー詳細（管理画面）</h1>
        <table class="user_show_table">
          <tr>
            <th><%= t('activerecord.attributes.user.name') %></th>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <th><%= t('activerecord.attributes.user.email') %></th>
            <td><%= @user.email %></td>
          </tr>
          <tr>
            <th><%= t('activerecord.attributes.user.created_at') %></th>
            <td><%= l @user.created_at %></td>
          </tr>
        </table>

        <%= link_to t('buttons.task_edit'), edit_admin_user_path(@user), class: "new_submit_btn btn btn-primary admin_new_btn" %>
        <hr>
        <br>
        <h1 class="admin_index_h1">ユーザー作成ラベル（管理画面）</h1>
        <ul class="show_labels" >
          <% @labels.each do |label| %>
            <li class="show_label">
              <span class="user_label user_show_label"><%= label.label_name %></span>
            </li>
          <% end %>
        </ul>
        <br>
        <br>
        <table class="table table-hover">
          <thead>
            <tr class="table_ths">
              <th class="first_th task_title_th"><%= t('activerecord.attributes.task.task_name') %></th>
              <th class="task_content_th"><%= t('activerecord.attributes.task.content') %></th>
              <th class="task_label_th">ラベル</th>
              <th class="task_priority_th"><%= t('activerecord.attributes.task.priority') %></th>
              <th class="task_limit_th"><%= t('activerecord.attributes.task.limit') %></th>
              <th class="task_status_th"><%= t('activerecord.attributes.task.status') %></th>
              <th class="task_created_at_th"><%= t('activerecord.attributes.task.created_at') %></th>
            </tr>
          </thead>

          <tbody class="task_tbody">
            <% @tasks.each do |task| %>
              <tr>
                <td class="task_title"><%= task.task_name %></td>
                <td><%= task.content %></td>
                <td>
                  <% task.labels.each do |label| %>
                    <% if label.official? %>
                      <span class="official_label label_index"><%= label.label_name %></span>
                    <% else %>
                      <span class="user_label label_index"><%= label.label_name %></span>
                    <% end %>
                  <% end %>
                </td>
                <td class="task_priority"><%= task.priority %></td>
                <td class="task_limit"><%= task.task_expired_at %></td>
                <td class="task_status"><%= task.status %></td>
                <td class="task_created_at"><%= l task.created_at %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @tasks %>

        <div class="show_btns">
          <%= link_to t('buttons.back'), admin_users_path %>
        </div>

      </div>

    </div>
  </div>
</div>