config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'

  resources :tasks do
    member do
      patch :file_purge
    end
  end

  resources :users, only: [:new, :create, :show]
  resources :labels, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources :labels, only: [:new, :create, :destroy]
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :groups
  resources :groupings, only: [:create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>People'sTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigation">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" id="header_logo" href="/">People'sTask</a>
        </div>
        <div class="collapse navbar-collapse" id="navigation">
          <div class="navbar-text navbar-right">
            <%= link_to new_task_path do %>
              <button type="button" class="btn btn-default navbar-btn">タスク作成</button>
            <% end %>
            <%= link_to tasks_path do %>
              <button type="button" class="btn btn-default navbar-btn">トップ</button>
            <% end %>

            <% if logged_in? %>
              <%= link_to user_path(current_user.id) do %>
                <button type="button" class="btn btn-default navbar-btn">ユーザー詳細</button>
              <% end %>
              <%= link_to groups_path do %>
                <button type="button" class="btn btn-default navbar-btn">グループ</button>
              <% end %>
              <%= link_to session_path(current_user.id), method: :delete do %>
                <button type="button" class="btn btn-default navbar-btn"　id="logout_button">ログアウト</button>
              <% end %>


              <% if current_user.admin? %>
                <%= link_to admin_users_path do %>
                  <button type="button" class="btn btn-default navbar-btn admin_new_btn" id="header_admin_button">ユーザー一覧（管理画面）へ</button>
                <% end %>
              <% end %>

            <% else %>
              <%= link_to new_user_path do %>
                <button type="button" class="btn btn-default navbar-btn">ユーザー登録</button>
              <% end %>
              <%= link_to new_session_path do %>
                <button type="button" class="btn btn-default navbar-btn">ログイン</button>
              <% end %>
            <% end %>

          </div>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>